### ISSUE TITLE
Reader

### ISSUE THREAD

**Issue by orion160** [Devil-Syntax-Tree/LLVM_sandbox#14]
Complete Reader
With FileReader and ConsoleReader implementations

**Comment by orion160** [comment]
Waiting for @nklopstock611 approval and discussion

**Comment by nklopstock611** [comment]
Reader class:

<img width="179" alt="image" src="https://github.com/Devil-Syntax-Tree/LLVM_sandbox/assets/77993013/d0546a46-452e-4487-9b75-958879cead5b">

Implementation of a ReaderFactory:

<img width="376" alt="image" src="https://github.com/Devil-Syntax-Tree/LLVM_sandbox/assets/77993013/53538ad5-d1f5-4ce9-a0be-60ad3e87d338">

Overcharge of the `createReader` function.

Child classes (ConsoleReader & FileReader):

ConsoleReader:

<img width="189" alt="image" src="https://github.com/Devil-Syntax-Tree/LLVM_sandbox/assets/77993013/f92c0f16-b00b-498e-a192-f4aef08de123">

FileReader:

<img width="212" alt="image" src="https://github.com/Devil-Syntax-Tree/LLVM_sandbox/assets/77993013/1174f24e-7e70-44f7-8bb5-78346ea77139">

Important to note that the `peekNextChar` functions could also have a particular implementation in the `Lexer` class.
